spring:
  profiles:
    active: local
  sql:
    init:
      mode: always
      platform: local

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:~/morak-dev;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true

---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:~/morak-dev;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
